export function setVariables(self) {
	const variables = [
		{ variableId: 'version', name: 'Version' },
		{ variableId: 'runtime', name: 'Runtime' },
		{ variableId: 'systime', name: 'System Time' },
		{ variableId: 'buildtime', name: 'Build Time' },
		{ variableId: 'cpuinfo', name: 'CPU Info' },
		{ variableId: 'vga_input', name: 'VGA Input' },
		{ variableId: 'sdi_input', name: 'SDI Input' },
		{ variableId: 'cpuusage', name: 'CPU Usage (%)' },
		{ variableId: 'memoryfree', name: 'Memory Free (kB)' },
		{ variableId: 'memorytotal', name: 'Memory Total (kB)' },
		{ variableId: 'net_packet_sent', name: 'Network Packets Sent' },
		{ variableId: 'net_packet_dropped', name: 'Network Packets Dropped' },
		{ variableId: 'ai_samplerate', name: 'Audio Input: Sample Rate (Hz)' },
		{ variableId: 'ai_audio_ok', name: 'Audio Input: Audio OK' },
		{ variableId: 'vi_framerate', name: 'Video Input: Frame Rate (Hz)' },
		{ variableId: 'vi_int_cnt', name: 'Video Input: Interrupt Count' },
		{ variableId: 'vi_lost_int', name: 'Video Input: Lost Interrupts' },
		{ variableId: 'vi_width', name: 'Video Input: Width' },
		{ variableId: 'vi_height', name: 'Video Input: Height' },
		{ variableId: 'vi_interlaced', name: 'Video Input: Interlaced' },
		{ variableId: 'vi_video_ok', name: 'Video Input: Video OK' },
		{ variableId: 'vi_mode', name: 'Video Input: Mode' },
		{ variableId: 'user_ts0', name: 'Active Users: MPEG-TS' },
		{ variableId: 'user_flv0', name: 'Active Users: FLV' },
		{ variableId: 'user_pri0', name: 'Active Users: PRI' },
		{ variableId: 'user_web', name: 'Active Users: Web' },
		{ variableId: 'user_rtsp', name: 'Active Users: RTSP' },
	]

	return variables
}
export function checkVariables(self) {
	self.setVariableValues({
		version: self.data.version,
		runtime: self.data.runtime,
		systime: self.data.systime,
		buildtime: self.data.buildtime,
		cpuinfo: self.data.cpuinfo,
		vga_input: !!self.data.vga_input,
		sdi_input: !!self.data.sdi_input,
		cpuusage: self.data.cpuusage,
		memoryfree: self.data.memoryfree,
		memorytotal: self.data.memorytotal,
		net_packet_sent: self.data.net_packet_sent,
		net_packet_dropped: self.data.net_packet_dropped,
		ai_samplerate: self.data.ai.samplerate,
		ai_audio_ok: !!self.data.ai.audio_ok ? 'Normal' : 'No Signal',
		vi_framerate: self.data.vi.framerate,
		vi_int_cnt: self.data.vi.int_cnt,
		vi_lost_int: self.data.vi.lost_int,
		vi_width: self.data.vi.width,
		vi_height: self.data.vi.height,
		vi_interlaced: !!self.data.vi.interlaced,
		vi_video_ok: !!self.data.vi.video_ok ? 'Normal' : 'No Signal',
		vi_mode: self.data.vi.height + (self.data.vi.interlaced ? 'i' : 'p') + self.data.vi.framerate,
		user_ts0: self.data.user.ts0,
		user_flv0: self.data.user.flv0,
		user_pri0: self.data.user.pri0,
		user_web: self.data.user.web,
		user_rtsp: self.data.user.rtsp,
	})
}
